### ISSUE TITLE
The example website for namor is down

### ISSUE THREAD

**Issue by corysimmons** [jsonmaur/namor#13]
https://namor-example.now.sh/

**Comment by jsonmaur** [comment]
Thanks Cory. If you take a look at the readme, the URL changed to https://namor-example.herokuapp.com a few years ago.

**Comment by corysimmons** [comment]
Oh, the README got updated on Github but not published to npm after it was updated:

![image](https://user-images.githubusercontent.com/224636/118275418-6229d400-b494-11eb-97bc-9539ff6bb011.png)

**Comment by jsonmaur** [comment]
Ah, good catch. I uploaded a new release to npm. Thanks!
